//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBHMA.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.HoaDonChiTiets = new HashSet<HoaDonChiTiet>();
        }
    
        public int ID { get; set; }
        public System.DateTime NgayDatHang { get; set; }
        [Display(Name ="Họ tên khách hàng")]
        public string HoTenKhach { get; set; }
        [Display(Name ="Địa chỉ")]
        public string DiaChi { get; set; }
        [Display(Name ="Số điện thoại")]
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public int TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonChiTiet> HoaDonChiTiets { get; set; }
    }
}
